[catalogue]
nom = "Catalogue ARCenal Client"
version = "0.1.0"
source_officielle = "https://app.yunohost.org/default/v3/apps.json"

[canaux.stable]
applications_yunohost = ["nextcloud", "dolibarr", "vaultwarden"]

[canaux.preview]
applications_yunohost = ["nextcloud", "dolibarr", "vaultwarden", "outline"]

[canaux.development]
applications_yunohost = ["nextcloud", "dolibarr", "vaultwarden", "outline", "vikunja"]

[[applications.arcenal]]
id = "arcenal-store"
nom = "ARCenal Store"
description_fr = "Active le catalogue ARCenal contrôlé dans YunoHost."
depot = "https://github.com/arcenal-coder/arcenal-store_ynh"
branche = "main"
revision = "efc25111312c9463f84cf7fa58d881e7e1cc9637"
canaux = ["stable", "preview", "development"]
version = "1.0.0~ynh1"
minimum_yunohost = ">= 12.1"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disque = "1M"
ram_build = "10M"
ram_runtime = "10M"

[[applications.arcenal]]
id = "arcenal-systeme"
nom = "ARCenal Système"
description_fr = "Socle de catalogue contrôlé et d'expérience ARCenal pour YunoHost."
depot = "https://github.com/arcenal-coder/arcenal-systeme_ynh"
branche = "main"
revision = "7b2f06cd1ad88362976eff0c86f4c74562390f45"
canaux = ["stable", "preview", "development"]
version = "0.6.0~ynh1"
minimum_yunohost = ">= 12.1"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disque = "1M"
ram_build = "10M"
ram_runtime = "10M"

[[applications.arcenal]]
id = "arcenalportail"
nom = "ARCenal Portail"
description_fr = "Portail équipier QSSE relié au module Dolibarr ARCenal QSSE."
depot = "https://github.com/arcenal-coder/arcenalportail_ynh"
branche = "main"
canaux = ["preview", "development"]
version = "0.4.4~beta1+ynh1"
minimum_yunohost = ">= 12.1"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disque = "10M"
ram_build = "50M"
ram_runtime = "50M"
